#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    May 12, 2025 12:19:34 AM %z  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import interfazInicial_support

_bgcolor = 'wheat'
_fgcolor = 'black'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("460x509+565+119")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#c0c0c0")
        top.configure(highlightbackground="#fdaaee")
        top.configure(highlightcolor="black")

        self.top = top

        self.Label2 = tk.Label(self.top)
        self.Label2.place(relx=0.046, rely=0.077, height=95, width=313)
        self.Label2.configure(activebackground="#d9d9d9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#c0c0c0")
        self.Label2.configure(compound='left')
        self.Label2.configure(cursor="fleur")
        self.Label2.configure(disabledforeground="#b8a786")
        self.Label2.configure(font="-family {System} -size 10 -weight bold")
        self.Label2.configure(foreground="black")
        self.Label2.configure(highlightbackground="wheat")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Participantes: Jim Gabriel Ariñez Bautista  
Yuri Daniel Ayaviri Quispe 
Humberto Alejandro Campos Torrejón  
Fabricio Alejandro Herrera Rojas  
Adam Jhoel Mamani 
Camila Belen Quispe Flores''')

        self.Label5 = tk.Label(self.top)
        self.Label5.place(relx=0.435, rely=0.491, height=261, width=284)
        self.Label5.configure(activebackground="#d9d9d9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(anchor='w')
        self.Label5.configure(background="#c0c0c0")
        self.Label5.configure(compound='left')
        self.Label5.configure(disabledforeground="#b8a786")
        self.Label5.configure(foreground="black")
        self.Label5.configure(highlightbackground="#edd3fe")
        self.Label5.configure(highlightcolor="black")
        photo_location = os.path.join(_location,"./si.png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Label5.configure(image=_img0)

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.043, rely=0.02, height=24, width=215)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#c0c0c0")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#b8a786")
        self.Label1.configure(font="-family {System} -size 10 -weight bold")
        self.Label1.configure(foreground="black")
        self.Label1.configure(highlightbackground="wheat")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Clasificacion de canciones''')

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.065, rely=0.295, height=26, width=247)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#edd3fe")
        self.Button1.configure(disabledforeground="#b8a786")
        self.Button1.configure(font="-family {Rustic Story} -size 9 -weight bold -slant italic")
        self.Button1.configure(foreground="black")
        self.Button1.configure(highlightbackground="wheat")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(text='''Seleccionar archivo''')

        self.Label3 = tk.Label(self.top)
        self.Label3.place(relx=0.043, rely=0.393, height=60, width=235)
        self.Label3.configure(activebackground="#d9d9d9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#c0c0c0")
        self.Label3.configure(compound='left')
        self.Label3.configure(cursor="fleur")
        self.Label3.configure(disabledforeground="#b8a786")
        self.Label3.configure(font="-family {System} -size 10 -weight bold")
        self.Label3.configure(foreground="black")
        self.Label3.configure(highlightbackground="wheat")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Características extraídas:              
BPM:              
Género real:              
Duración:''')

        self.Button2 = tk.Button(self.top)
        self.Button2.place(relx=0.065, rely=0.53, height=26, width=117)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="black")
        self.Button2.configure(background="#edd3fe")
        self.Button2.configure(disabledforeground="#b8a786")
        self.Button2.configure(font="-family {Rustic Story} -size 9 -weight bold -slant italic")
        self.Button2.configure(foreground="black")
        self.Button2.configure(highlightbackground="wheat")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(text='''Clasificar Cancion''')

        self.Label4 = tk.Label(self.top)
        self.Label4.place(relx=0.043, rely=0.589, height=72, width=164)
        self.Label4.configure(activebackground="#d9d9d9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(anchor='w')
        self.Label4.configure(background="#c0c0c0")
        self.Label4.configure(compound='left')
        self.Label4.configure(disabledforeground="#b8a786")
        self.Label4.configure(font="-family {System} -size 10 -weight bold")
        self.Label4.configure(foreground="black")
        self.Label4.configure(highlightbackground="wheat")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Resultado:                                   
Género predicho:                 
Agente reward:''')

def start_up():
    interfazInicial_support.main()

if __name__ == '__main__':
    interfazInicial_support.main()




