#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  May 11, 2025 11:26:44 PM %z  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
    si_png "./si.png" 
}
vTcl:create_project_images $image_list   ;# In image.tcl

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) page-wheat



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #c0c0c0 -highlightbackground #fdaaee \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 460x509+565+119
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1540 845
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    label "$top.lab48" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #c0c0c0 -compound left -disabledforeground #b8a786 \
        -font "-family {System} -size 10 -weight bold" -foreground black \
        -highlightbackground wheat -highlightcolor black \
        -text "Participantes: Jim Gabriel Ariñez Bautista  
Yuri Daniel Ayaviri Quispe 
Humberto Alejandro Campos Torrejón  
Fabricio Alejandro Herrera Rojas  
Adam Jhoel Mamani 
Camila Belen Quispe Flores " 
    vTcl:DefineAlias "$top.lab48" "Label2" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but49" \
        -activebackground #d9d9d9 -activeforeground black -background #edd3fe \
        -disabledforeground #b8a786 \
        -font "-family {Rustic Story} -size 9 -weight bold -slant italic" \
        -foreground black -highlightbackground wheat -highlightcolor black \
        -text "Seleccionar archivo" 
    vTcl:DefineAlias "$top.but49" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab53" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #c0c0c0 -compound left -disabledforeground #b8a786 \
        -font "-family {System} -size 10 -weight bold" -foreground black \
        -highlightbackground wheat -highlightcolor black \
        -text "Resultado:                                   
Género predicho:                 
Agente reward:" 
    vTcl:DefineAlias "$top.lab53" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab58" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #c0c0c0 -compound left -disabledforeground #b8a786 \
        -font "-family {Segoe UI} -size 9" -foreground black \
        -highlightbackground #edd3fe -highlightcolor black -image si_png 
    vTcl:DefineAlias "$top.lab58" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab47" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #c0c0c0 -compound left -disabledforeground #b8a786 \
        -font "-family {System} -size 10 -weight bold" -foreground black \
        -highlightbackground wheat -highlightcolor black \
        -text "Clasificacion de canciones" 
    vTcl:DefineAlias "$top.lab47" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #c0c0c0 -compound left -disabledforeground #b8a786 \
        -font "-family {System} -size 10 -weight bold" -foreground black \
        -highlightbackground wheat -highlightcolor black \
        -text "Características extraídas:              
BPM:              
Género real:              
Duración: " 
    vTcl:DefineAlias "$top.lab51" "Label3" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but52" \
        -activebackground #d9d9d9 -activeforeground black -background #edd3fe \
        -disabledforeground #b8a786 \
        -font "-family {Rustic Story} -size 9 -weight bold -slant italic" \
        -foreground black -highlightbackground wheat -highlightcolor black \
        -text "Clasificar Cancion" 
    vTcl:DefineAlias "$top.but52" "Button2" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab48 \
        -in $top -x 0 -relx 0.046 -y 0 -rely 0.077 -width 0 -relwidth 0.68 \
        -height 0 -relheight 0.187 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.043 -y 0 -rely 0.295 -width 247 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 0 -relx 0.043 -y 0 -rely 0.589 -width 0 -relwidth 0.357 \
        -height 0 -relheight 0.141 -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 0 -relx 0.435 -y 0 -rely 0.491 -width 0 -relwidth 0.617 \
        -height 0 -relheight 0.513 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.043 -y 0 -rely 0.02 -width 0 -relwidth 0.467 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.045 -y 0 -rely 0.385 -width 0 -relwidth 0.51 \
        -height 0 -relheight 0.117 -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 0 -relx 0.043 -y 0 -rely 0.53 -width 117 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

