# Generated by Django 5.2.1 on 2025-05-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(db_index=True, max_length=200, unique=True)),
                ('genre', models.CharField(db_index=True, max_length=50)),
                ('tempo', models.FloatField()),
                ('rms', models.FloatField(verbose_name='Energy')),
                ('centroid', models.FloatField(verbose_name='Spectral Centroid')),
                ('mfccs', models.JSONField()),
            ],
            options={
                'verbose_name': 'Song Feature',
                'verbose_name_plural': 'Song Features',
                'db_table': 'song_features',
                'indexes': [models.Index(fields=['genre'], name='song_featur_genre_e30889_idx'), models.Index(fields=['tempo'], name='song_featur_tempo_79a9d8_idx')],
            },
        ),
    ]
